// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Entries.Batch;
using ApiSdk.Entries.Cursor;
using ApiSdk.Entries.Imports;
using ApiSdk.Entries.Item;
using ApiSdk.Entries.Stats;
using ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero;
using ApiSdk.Models.DevHabit.Api.DTOs.Entries;
using ApiSdk.Models.Microsoft.AspNetCore.Mvc;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Entries
{
    /// <summary>
    /// Builds and executes requests for operations under \entries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batch property</summary>
        public global::ApiSdk.Entries.Batch.BatchRequestBuilder Batch
        {
            get => new global::ApiSdk.Entries.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cursor property</summary>
        public global::ApiSdk.Entries.Cursor.CursorRequestBuilder Cursor
        {
            get => new global::ApiSdk.Entries.Cursor.CursorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The imports property</summary>
        public global::ApiSdk.Entries.Imports.ImportsRequestBuilder Imports
        {
            get => new global::ApiSdk.Entries.Imports.ImportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::ApiSdk.Entries.Stats.StatsRequestBuilder Stats
        {
            get => new global::ApiSdk.Entries.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ApiSdk.entries.item collection</summary>
        /// <param name="position">The entry ID</param>
        /// <returns>A <see cref="global::ApiSdk.Entries.Item.EntriesItemRequestBuilder"/></returns>
        public global::ApiSdk.Entries.Item.EntriesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ApiSdk.Entries.Item.EntriesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Entries.EntriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/entries{?fields*,fromDate*,habitId*,includeLinks*,isArchived*,page*,pageSize*,sort*,source*,toDate*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Entries.EntriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/entries{?fields*,fromDate*,habitId*,includeLinks*,isArchived*,page*,pageSize*,sort*,source*,toDate*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a paginated list of entries
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Entries.EntriesRequestBuilder.EntriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull> GetAsync(Action<RequestConfiguration<global::ApiSdk.Entries.EntriesRequestBuilder.EntriesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull>(requestInfo, global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new entry
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto?> PostAsync(global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.CreateEntryDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto> PostAsync(global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.CreateEntryDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto>(requestInfo, global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a paginated list of entries
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Entries.EntriesRequestBuilder.EntriesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Entries.EntriesRequestBuilder.EntriesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;v=1, application/vnd.dev-habit.hateoas+json, application/vnd.dev-habit.hateoas.1+json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new entry
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.CreateEntryDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.CreateEntryDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;v=1, application/vnd.dev-habit.hateoas+json, application/vnd.dev-habit.hateoas.1+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;v=1.0", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Entries.EntriesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Entries.EntriesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Entries.EntriesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a paginated list of entries
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EntriesRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            [QueryParameter("fromDate")]
            public Date? FromDate { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("habitId")]
            public string? HabitId { get; set; }
#nullable restore
#else
            [QueryParameter("habitId")]
            public string HabitId { get; set; }
#endif
            [QueryParameter("includeLinks")]
            public bool? IncludeLinks { get; set; }
            [QueryParameter("isArchived")]
            public bool? IsArchived { get; set; }
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            [QueryParameter("source")]
            public int? Source { get; set; }
            [QueryParameter("toDate")]
            public Date? ToDate { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EntriesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Entries.EntriesRequestBuilder.EntriesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EntriesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
