// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models.DevHabit.Api.DTOs.Common;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models.DevHabit.Api.DTOs.Habits
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HabitDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The automationSource property</summary>
        public int? AutomationSource { get; set; }
        /// <summary>The createdAtUtc property</summary>
        public DateTimeOffset? CreatedAtUtc { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endDate property</summary>
        public Date? EndDate { get; set; }
        /// <summary>The frequency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.FrequencyDto? Frequency { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.FrequencyDto Frequency { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isArchived property</summary>
        public bool? IsArchived { get; set; }
        /// <summary>The lastCompletedAtUtc property</summary>
        public DateTimeOffset? LastCompletedAtUtc { get; set; }
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>? Links { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto> Links { get; set; }
#endif
        /// <summary>The milestone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.MilestoneDto? Milestone { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.MilestoneDto Milestone { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.TargetDto? Target { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.TargetDto Target { get; set; }
#endif
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>The updatedAtUtc property</summary>
        public DateTimeOffset? UpdatedAtUtc { get; set; }
        /// <summary>The userId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.HabitDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.HabitDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.HabitDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "automationSource", n => { AutomationSource = n.GetIntValue(); } },
                { "createdAtUtc", n => { CreatedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetDateValue(); } },
                { "frequency", n => { Frequency = n.GetObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.FrequencyDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.FrequencyDto.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isArchived", n => { IsArchived = n.GetBoolValue(); } },
                { "lastCompletedAtUtc", n => { LastCompletedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "milestone", n => { Milestone = n.GetObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.MilestoneDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.MilestoneDto.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.TargetDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.TargetDto.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "updatedAtUtc", n => { UpdatedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("automationSource", AutomationSource);
            writer.WriteDateTimeOffsetValue("createdAtUtc", CreatedAtUtc);
            writer.WriteStringValue("description", Description);
            writer.WriteDateValue("endDate", EndDate);
            writer.WriteObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.FrequencyDto>("frequency", Frequency);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isArchived", IsArchived);
            writer.WriteDateTimeOffsetValue("lastCompletedAtUtc", LastCompletedAtUtc);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>("links", Links);
            writer.WriteObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.MilestoneDto>("milestone", Milestone);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("status", Status);
            writer.WriteObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.Habits.TargetDto>("target", Target);
            writer.WriteIntValue("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAtUtc", UpdatedAtUtc);
            writer.WriteStringValue("userId", UserId);
        }
    }
}
#pragma warning restore CS0618
