// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Auth;
using ApiSdk.Entries;
using ApiSdk.Github;
using ApiSdk.Habits;
using ApiSdk.Tags;
using ApiSdk.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DevHabitClient : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::ApiSdk.Auth.AuthRequestBuilder Auth
        {
            get => new global::ApiSdk.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The entries property</summary>
        public global::ApiSdk.Entries.EntriesRequestBuilder Entries
        {
            get => new global::ApiSdk.Entries.EntriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The github property</summary>
        public global::ApiSdk.Github.GithubRequestBuilder Github
        {
            get => new global::ApiSdk.Github.GithubRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The habits property</summary>
        public global::ApiSdk.Habits.HabitsRequestBuilder Habits
        {
            get => new global::ApiSdk.Habits.HabitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::ApiSdk.Tags.TagsRequestBuilder Tags
        {
            get => new global::ApiSdk.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::ApiSdk.Users.UsersRequestBuilder Users
        {
            get => new global::ApiSdk.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.DevHabitClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DevHabitClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
