// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models.DevHabit.Api.DTOs.GitHub
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GitHubEventDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubActorDto? Actor { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubActorDto Actor { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isPublic property</summary>
        public bool? IsPublic { get; set; }
        /// <summary>The payload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubPayloadDto? Payload { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubPayloadDto Payload { get; set; }
#endif
        /// <summary>The repository property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubRepositoryDto? Repository { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubRepositoryDto Repository { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubEventDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubEventDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubEventDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actor", n => { Actor = n.GetObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubActorDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubActorDto.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isPublic", n => { IsPublic = n.GetBoolValue(); } },
                { "payload", n => { Payload = n.GetObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubPayloadDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubPayloadDto.CreateFromDiscriminatorValue); } },
                { "repository", n => { Repository = n.GetObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubRepositoryDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubRepositoryDto.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubActorDto>("actor", Actor);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isPublic", IsPublic);
            writer.WriteObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubPayloadDto>("payload", Payload);
            writer.WriteObjectValue<global::ApiSdk.Models.DevHabit.Api.DTOs.GitHub.GitHubRepositoryDto>("repository", Repository);
            writer.WriteStringValue("type", Type);
        }
    }
}
#pragma warning restore CS0618
