@DevHabit.Api_HostAddress = https://localhost:5001

GET {{DevHabit.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DevHabit.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###