// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models.DevHabit.Api.DTOs.Common.CollectionResponse1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero;
using ApiSdk.Models.Microsoft.AspNetCore.Mvc;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Entries.Cursor
{
    /// <summary>
    /// Builds and executes requests for operations under \entries\cursor
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CursorRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Entries.Cursor.CursorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CursorRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/entries/cursor{?cursor*,fields*,fromDate*,habitId*,includeLinks*,isArchived*,limit*,source*,toDate*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Entries.Cursor.CursorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CursorRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/entries/cursor{?cursor*,fields*,fromDate*,habitId*,includeLinks*,isArchived*,limit*,source*,toDate*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a cursor-based paginated list of entries
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Common.CollectionResponse1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.CollectionResponse1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Entries.Cursor.CursorRequestBuilder.CursorRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.CollectionResponse1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull> GetAsync(Action<RequestConfiguration<global::ApiSdk.Entries.Cursor.CursorRequestBuilder.CursorRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.CollectionResponse1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull>(requestInfo, global::ApiSdk.Models.DevHabit.Api.DTOs.Common.CollectionResponse1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a cursor-based paginated list of entries
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Entries.Cursor.CursorRequestBuilder.CursorRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Entries.Cursor.CursorRequestBuilder.CursorRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;v=1, application/vnd.dev-habit.hateoas+json, application/vnd.dev-habit.hateoas.1+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Entries.Cursor.CursorRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Entries.Cursor.CursorRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Entries.Cursor.CursorRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a cursor-based paginated list of entries
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CursorRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields")]
            public string? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields")]
            public string Fields { get; set; }
#endif
            [QueryParameter("fromDate")]
            public Date? FromDate { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("habitId")]
            public string? HabitId { get; set; }
#nullable restore
#else
            [QueryParameter("habitId")]
            public string HabitId { get; set; }
#endif
            [QueryParameter("includeLinks")]
            public bool? IncludeLinks { get; set; }
            [QueryParameter("isArchived")]
            public bool? IsArchived { get; set; }
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            [QueryParameter("source")]
            public int? Source { get; set; }
            [QueryParameter("toDate")]
            public Date? ToDate { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CursorRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Entries.Cursor.CursorRequestBuilder.CursorRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
