// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models.DevHabit.Api.DTOs.Common;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models.DevHabit.Api.DTOs.EntryImports
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntryImportJobDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The completedAtUtc property</summary>
        public DateTimeOffset? CompletedAtUtc { get; set; }
        /// <summary>The createdAtUtc property</summary>
        public DateTimeOffset? CreatedAtUtc { get; set; }
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Errors { get; set; }
#nullable restore
#else
        public List<string> Errors { get; set; }
#endif
        /// <summary>The failedRecords property</summary>
        public int? FailedRecords { get; set; }
        /// <summary>The fileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>? Links { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto> Links { get; set; }
#endif
        /// <summary>The processedRecords property</summary>
        public int? ProcessedRecords { get; set; }
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>The successfulRecords property</summary>
        public int? SuccessfulRecords { get; set; }
        /// <summary>The totalRecords property</summary>
        public int? TotalRecords { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.EntryImports.EntryImportJobDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DevHabit.Api.DTOs.EntryImports.EntryImportJobDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DevHabit.Api.DTOs.EntryImports.EntryImportJobDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedAtUtc", n => { CompletedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "createdAtUtc", n => { CreatedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "errors", n => { Errors = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "failedRecords", n => { FailedRecords = n.GetIntValue(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "processedRecords", n => { ProcessedRecords = n.GetIntValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "successfulRecords", n => { SuccessfulRecords = n.GetIntValue(); } },
                { "totalRecords", n => { TotalRecords = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedAtUtc", CompletedAtUtc);
            writer.WriteDateTimeOffsetValue("createdAtUtc", CreatedAtUtc);
            writer.WriteCollectionOfPrimitiveValues<string>("errors", Errors);
            writer.WriteIntValue("failedRecords", FailedRecords);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>("links", Links);
            writer.WriteIntValue("processedRecords", ProcessedRecords);
            writer.WriteIntValue("status", Status);
            writer.WriteIntValue("successfulRecords", SuccessfulRecords);
            writer.WriteIntValue("totalRecords", TotalRecords);
        }
    }
}
#pragma warning restore CS0618
