// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Habits.Item.Tags.Item;
using ApiSdk.Models.DevHabit.Api.DTOs.HabitTags;
using ApiSdk.Models.Microsoft.AspNetCore.Mvc;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Habits.Item.Tags
{
    /// <summary>
    /// Builds and executes requests for operations under \habits\{habit-id}\tags
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.habits.item.tags.item collection</summary>
        /// <param name="position">The ID of the tag to remove</param>
        /// <returns>A <see cref="global::ApiSdk.Habits.Item.Tags.Item.WithTagItemRequestBuilder"/></returns>
        public global::ApiSdk.Habits.Item.Tags.Item.WithTagItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tagId", position);
                return new global::ApiSdk.Habits.Item.Tags.Item.WithTagItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Habits.Item.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/habits/{habit%2Did}/tags", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Habits.Item.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/habits/{habit%2Did}/tags", rawUrl)
        {
        }
        /// <summary>
        /// Updates the tags associated with a habit
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 403 status code</exception>
        /// <exception cref="global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PutAsync(global::ApiSdk.Models.DevHabit.Api.DTOs.HabitTags.UpsertHabitTagsDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PutAsync(global::ApiSdk.Models.DevHabit.Api.DTOs.HabitTags.UpsertHabitTagsDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "403", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::ApiSdk.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the tags associated with a habit
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::ApiSdk.Models.DevHabit.Api.DTOs.HabitTags.UpsertHabitTagsDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::ApiSdk.Models.DevHabit.Api.DTOs.HabitTags.UpsertHabitTagsDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;v=1, application/vnd.dev-habit.hateoas+json, application/vnd.dev-habit.hateoas.1+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;v=1.0", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Habits.Item.Tags.TagsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Habits.Item.Tags.TagsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Habits.Item.Tags.TagsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
