// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models.DevHabit.Api.DTOs.Common;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models.DevHabit.Api.DTOs.Users
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdAtUtc property</summary>
        public DateTimeOffset? CreatedAtUtc { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>? Links { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto> Links { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The updatedAtUtc property</summary>
        public DateTimeOffset? UpdatedAtUtc { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Users.UserDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DevHabit.Api.DTOs.Users.UserDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DevHabit.Api.DTOs.Users.UserDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAtUtc", n => { CreatedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "updatedAtUtc", n => { UpdatedAtUtc = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAtUtc", CreatedAtUtc);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>("links", Links);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("updatedAtUtc", UpdatedAtUtc);
        }
    }
}
#pragma warning restore CS0618
