// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models.DevHabit.Api.DTOs.Entries
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntryStatsDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The currentStreak property</summary>
        public int? CurrentStreak { get; set; }
        /// <summary>The dailyStats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.DailyStatsDto>? DailyStats { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.DailyStatsDto> DailyStats { get; set; }
#endif
        /// <summary>The longestStreak property</summary>
        public int? LongestStreak { get; set; }
        /// <summary>The totalEntries property</summary>
        public int? TotalEntries { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryStatsDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryStatsDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryStatsDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentStreak", n => { CurrentStreak = n.GetIntValue(); } },
                { "dailyStats", n => { DailyStats = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.DailyStatsDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.DailyStatsDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "longestStreak", n => { LongestStreak = n.GetIntValue(); } },
                { "totalEntries", n => { TotalEntries = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentStreak", CurrentStreak);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.DailyStatsDto>("dailyStats", DailyStats);
            writer.WriteIntValue("longestStreak", LongestStreak);
            writer.WriteIntValue("totalEntries", TotalEntries);
        }
    }
}
#pragma warning restore CS0618
