// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Github.Events;
using ApiSdk.Github.PersonalAccessToken;
using ApiSdk.Github.Profile;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Github
{
    /// <summary>
    /// Builds and executes requests for operations under \github
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GithubRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The events property</summary>
        public global::ApiSdk.Github.Events.EventsRequestBuilder Events
        {
            get => new global::ApiSdk.Github.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The personalAccessToken property</summary>
        public global::ApiSdk.Github.PersonalAccessToken.PersonalAccessTokenRequestBuilder PersonalAccessToken
        {
            get => new global::ApiSdk.Github.PersonalAccessToken.PersonalAccessTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::ApiSdk.Github.Profile.ProfileRequestBuilder Profile
        {
            get => new global::ApiSdk.Github.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Github.GithubRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GithubRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/github", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Github.GithubRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GithubRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/github", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
