// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models.DevHabit.Api.DTOs.Entries;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ZeroCultureNeutralPublicKeyTokenNull : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The hasNextPage property</summary>
        public bool? HasNextPage { get; private set; }
        /// <summary>The hasPreviousPage property</summary>
        public bool? HasPreviousPage { get; private set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto>? Items { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto> Items { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>? Links { get; set; }
#nullable restore
#else
        public List<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto> Links { get; set; }
#endif
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>The totalPages property</summary>
        public int? TotalPages { get; private set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.DevHabit.Api.DTOs.Common.PaginationResult1DevHabit.Api.DTOs.Entries.EntryDtoDevHabit.ApiVersion1.Zero.Zero.ZeroCultureNeutralPublicKeyTokenNull();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hasNextPage", n => { HasNextPage = n.GetBoolValue(); } },
                { "hasPreviousPage", n => { HasPreviousPage = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>(global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Entries.EntryDto>("items", Items);
            writer.WriteCollectionOfObjectValues<global::ApiSdk.Models.DevHabit.Api.DTOs.Common.LinkDto>("links", Links);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteIntValue("totalCount", TotalCount);
        }
    }
}
#pragma warning restore CS0618
